spring.application.name=PM-Service-Reports
server.port=8090

# PostgreSQL Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Digital_EForm
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable Hidden HTTP Methods (PUT, DELETE)
spring.mvc.hiddenmethod.filter.enabled=true
logging.level.org.springframework.security=DEBUG

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Optional
spring.devtools.restart.additional-paths=src/main/java,src/main/resources

